server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  session:
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.MiaoShaSystem.entity
  configuration:
    map-underscore-to-camel-case: true
file:
  upload-dir: ./uploads/          # 相对路径，会在项目根目录创建
  access-prefix: /uploads/         # 访问 URL 前缀

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket: seckill-system-lzx
    region: cn-hangzhou
    role-arn: acs:ram::1275534496191707:role/seckill-sts-role
    access-key-id: ${OSS_AK_ID:}                  # ← 从环境变量读
    access-key-secret: ${OSS_AK_SECRET:}          # ← 从环境变量读